LunarWebShop/Controllers/SorteerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logic;
using Models;

namespace LunarWebShop.Controllers
{
    public class SorteerController : Controller
    {
        ProductLogic Productlogic = new ProductLogic();
        public ActionResult IndexSearch()
        {
            return View();
        }
        public ActionResult IndexGenre(string genre)
        {
            List<Product> producten = new List<Product>();
            if (genre == "Action")
            {
                producten = Productlogic.ProductenGenre(Genre.Action);
            }
            if (genre == "Adventure")
            {
                producten = Productlogic.ProductenGenre(Genre.Adventure);
            }
            if (genre == "Fighting")
            {
                producten = Productlogic.ProductenGenre(Genre.Fighting);
            }
            if (genre == "Platform")
            {
                producten = Productlogic.ProductenGenre(Genre.Platform);
            }
            if (genre == "Puzzle")
            {
                producten = Productlogic.ProductenGenre(Genre.Puzzle);
            }
            if (genre == "Racing")
            {
                producten = Productlogic.ProductenGenre(Genre.Racing);
            }
            if (genre == "RolePlaying")
            {
                producten = Productlogic.ProductenGenre(Genre.RolePlaying);
            }
            if (genre == "Shooter")
            {
                producten = Productlogic.ProductenGenre(Genre.Shooter);
            }
            if (genre == "Simulation")
            {
                producten = Productlogic.ProductenGenre(Genre.Simulation);
            }
            if (genre == "Sports")
            {
                producten = Productlogic.ProductenGenre(Genre.Sports);
            }
            if (genre == "Strategy")
            {
                producten = Productlogic.ProductenGenre(Genre.Strategy);
            }
            if (genre == "Mmorpg")
            {
                producten = Productlogic.ProductenGenre(Genre.Mmorpg);
            }
            return View(producten);
        }
        public ActionResult IndexPrijsLaagNaarHoog()
        {
            return View(Productlogic.ProductenPrijsLaagHoog());
        }
        public ActionResult IndexPrijsHoogNaarLaag()
        {
            return View(Productlogic.ProductenPrijsHoogLaag());
        }
    }
}

LunarWebShop/Controllers/WinkelwagenManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.DynamicData;
using System.Web.Mvc;
using Logic;
using Models;

namespace LunarWebShop.Controllers
{
    public class WinkelwagenManagementController : Controller
    {
        private GebruikerLogic GebruikerLogic = new GebruikerLogic();

        public ActionResult Add(int KlantID, int ProductID)
        {
            GebruikerLogic.VoegToeAanWinkelwagen(KlantID, ProductID);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Myorder(int id)
        {

            List<Product> producten = GebruikerLogic.WinkelwagenProducten(id);
            ViewModelProductKeycodeList VMPK = new ViewModelProductKeycodeList();
            foreach (var item in producten)
            {
                VMPK.Product.Add(item);
                VMPK.TotaalBedrag = VMPK.TotaalBedrag + item.Prijs;
            }

            if (TempData["Message"] != null)
            {
                if (TempData["Message"].ToString().Contains("Onvoldoende Saldo"))
                {
                    ViewBag.Message = TempData["Message"];
                    ViewBag.Status = false;
                    return View(VMPK);
                }
            }
            return View(VMPK);
        }
        public ActionResult Remove(int KeycodeID,int productid, int id)
        {
            GebruikerLogic.VerwijderUitWinkelwagen(KeycodeID, productid, id);
            return RedirectToAction("Myorder", new{id = id});
        }

      
    }


}

LunarWebShop/Views/Shared/_Layout.cshtml
@using System.Security.Policy
@using System.Web.UI.WebControls
@using Models
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Lunar</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>


</head>
<body style="padding-top: 0px; text-align: left;">
    @{
        var klant = Session["Klant"] as Klant;
        var admin = Session["Administrator"] as Administrator;
    }

    @if (klant != null || admin != null)
    {
        if (klant != null)
        {
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="@Url.Action("Index", "Home")">Lunar</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("GameBibliotheek", "Klant", new { id = @klant.KlantID })">Mijn games</a></li>
                        <li><a href="@Url.Action("SaldoUploaden", "Klant", new { id = @klant.KlantID, gebruikersnaam = @klant.Gebruikersnaam })">Saldo uploaden</a></li>
                        <li><a href="@Url.Action("MijnAccount", "Klant", new { @style = "color:White;" })">Account</a></li>
                        <li><a href="@Url.Action("Myorder", "WinkelwagenManagement", new { id = @klant.KlantID })">Winkelwagen</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li> <a>Welkom, @klant.Voornaam Saldo : €@klant.Saldo</a></li>
                        <li><a href="@Url.Action("Uitloggen", "Klant", new {@style = "color:White;"})">Uitloggen</a></li>
                    </ul>
                </div>
            </nav>
            <div class="navbar2 navbar-default navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".main-nav">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse main-nav">
                        <ul class="nav navbar-nav">
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Action" }, null)">Action</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Adventure" }, null)">Adventure</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Fighting" }, null)">Fighting</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Platform" }, null)">Platform</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Puzzle" }, null)">Puzzle</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Racing" }, null)">Racing</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "RolePlaying" }, null)">RolePlaying</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Shooter" }, null)">Shooter</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Simulation" }, null)">Simulation</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Sports" }, null)">Sports</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Strategy" }, null)">Strategy</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Mmorpg" }, null)">Mmorpg</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexPrijsHoogNaarLaag", "Sorteer",null)">Prijs hoog - laag</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexPrijsLaagNaarHoog", "Sorteer",  null)">Prijs laag - hoog</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        }
        if (admin != null)
        {

            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="@Url.Action("Index", "Home")">Lunar</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a>Welkom Admin, @admin.Voornaam @admin.Achternaam</a></li>
                        <li><a href="@Url.Action("Product", "Producten",new { @style = "color:White;" })">Dashboard</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Uitloggen", "Klant",  new { @style = "color:White;" })">Uitloggen</a></li>
                    </ul>
                </div>
            </nav>
            <div class="navbar2 navbar-default navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".main-nav">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse main-nav">
                        <ul class="nav navbar-nav">
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Action" }, null)">Action</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Adventure" }, null)">Adventure</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Fighting" }, null)">Fighting</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Platform" }, null)">Platform</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Puzzle" }, null)">Puzzle</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Racing" }, null)">Racing</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "RolePlaying" }, null)">RolePlaying</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Shooter" }, null)">Shooter</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Simulation" }, null)">Simulation</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Sports" }, null)">Sports</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Strategy" }, null)">Strategy</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Mmorpg" }, null)">Mmorpg</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexPrijsHoogNaarLaag", "Sorteer",null)">Prijs hoog - laag</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="@Url.Action("IndexPrijsLaagNaarHoog", "Sorteer",  null)">Prijs laag - hoog</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        }
    }
    else
    {

        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")">Lunar</a>
                </div>
                <ul class="nav navbar-nav"></ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Login", "Klant",new { @style = "color:#FFFFFF;" })">Inloggen</a></li>
                    <li><a href="@Url.Action("RegistratieKlant", "Klant", new { @style = "color:#FFFFFF;" })">Registreren</a></li>
                </ul>
            </div>
        </nav>
        <div class="navbar2 navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".main-nav">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse main-nav">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Action" }, null)">Action</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Adventure" }, null)">Adventure</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Fighting" }, null)">Fighting</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Platform" }, null)">Platform</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Puzzle" }, null)">Puzzle</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Racing" }, null)">Racing</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "RolePlaying" }, null)">RolePlaying</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Shooter" }, null)">Shooter</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Simulation" }, null)">Simulation</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Sports" }, null)">Sports</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Strategy" }, null)">Strategy</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexGenre", "Sorteer", new { genre = "Mmorpg" }, null)">Mmorpg</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexPrijsHoogNaarLaag", "Sorteer",null)">Prijs hoog - laag</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="@Url.Action("IndexPrijsLaagNaarHoog", "Sorteer",  null)">Prijs laag - hoog</a></li>
                    </ul>
                </div>
            </div>
        </div>
    }

    @RenderBody()

    <footer>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <script src="/Scripts/Jeremy.js"></script>
    </footer>
</body>
</html>